 @host = https://localhost:5001

GET {{host}}/api/UserAndPassword
Accept: application/json

###

POST {{host}}/api/UserAndPassword/register
Content-Type: application/json

{
  "username": "paavo",
  "password": "opettaja"
}

###

PUT {{host}}/api/UserAndPassword/update
Content-Type: application/json

{
  "username": "paavo",
  "password": "newPassword123"
}

###

DELETE https://localhost:5001/api/UserAndPassword/delete/paavo
Accept: application/json


###

